### ISSUE TITLE
Unable to run app on phone with ember-cli-cordova-utils installed.

### ISSUE THREAD

**Issue by jarredkenny** [poetic/ember-cli-cordova-utils#5]
Hello,

I have an Ember app and I am using ember-cli-cordova to build it for Android. I am buiding and installing the app on my phone using the following commands.

```
ember cordova:build --platform=android
adb install ./cordova/platforms/android/ant-build/CordovaApp-debug.apk
```

This works fine until I install the `ember-cli-cordova-utils` plugin. Once installed, I rebuild the APK and deploy it to my phone. Only now, I see a white screen instead of my app. I was able to view the phones system logs over adb and am seeing this error:

```
01-21 15:11:03.080  20317-20317/com.jobit.app D/CordovaLog﹕ file:///android_asset/www/assets/vendor.js: Line 28585 : DEBUG: -------------------------------
01-21 15:11:03.080  20317-20317/com.jobit.app D/CordovaLog﹕ file:///android_asset/www/assets/vendor.js: Line 28585 : DEBUG: Ember      : 1.8.1
01-21 15:11:03.080  20317-20317/com.jobit.app D/CordovaLog﹕ file:///android_asset/www/assets/vendor.js: Line 28585 : DEBUG: Ember Data : 1.0.0-beta.12
01-21 15:11:03.081  20317-20317/com.jobit.app D/CordovaLog﹕ file:///android_asset/www/assets/vendor.js: Line 28585 : DEBUG: Handlebars : 1.3.0
01-21 15:11:03.081  20317-20317/com.jobit.app D/CordovaLog﹕ file:///android_asset/www/assets/vendor.js: Line 28585 : DEBUG: jQuery     : 1.11.2
01-21 15:11:03.082  20317-20317/com.jobit.app D/CordovaLog﹕ file:///android_asset/www/assets/vendor.js: Line 28585 : DEBUG: -------------------------------
01-21 15:11:03.186  20317-20317/com.jobit.app D/CordovaActivity﹕ onMessage(spinner,stop)
01-21 15:11:03.566  20317-20317/com.jobit.app D/CordovaLog﹕ file:///android_asset/www/assets/vendor.js: Line 76697 : Uncaught TypeError: Cannot read property 'addEventListener' of undefined
```

After looking for that line number in my vendor.js file, it appears to be caused by this code.

```
/**
 * addEventListener with multiple events at once
 * @param {EventTarget} target
 * @param {String} types
 * @param {Function} handler
 */
function addEventListeners(target, types, handler) {
    each(splitStr(types), function(type) {
        target.addEventListener(type, handler, false);
    });
}
```

Do you have any idea why this is happening?

**Comment by jakecraige** [comment]
Interesting. The only place the addEventListener api is being used is [here](https://github.com/poetic/ember-cli-cordova-utils/blob/a9709796bd512a907bde964845d663f1bb592361/app/initializers/cordova.js#L10). If you use [chrome://inspect](chrome://inspect) with your device plugged in and `location.reload()` the app from the developer console, it may give you a better stack trace to reference. 

It's like the document isn't on available yet or something, which seems weird.

**Comment by jarredkenny** [comment]
Using `chrome://inspect` I was able to get a regular shell and see the real error. It does not look like ember-cli-cordova-utils is the problem, but rather I am using it wrong. 

I have a UI controller responsible for setting up the UI depending on the type of device. This controller is required by my application controller so it gets instantiated right away. Within this controller I have a setup method that is called on the 'init' event. However, I think this is too early in the applications life cycle to for ember-cli-cordova-utils to detect which type of device it is.

```
setup: function(){
    Ember.Logger.log(this.get('device.isAndroid')); // this logs false.
    document.addEventListener('deviceready', function(){
        Ember.Logger.log(this.get('device.isAndroid')); // this also logs false
    }.bind(this));
}.on('init')
```

When is it safe to check the device?

Thank you,
Jarred

**Comment by jakecraige** [comment]
When this utils lib is added it actually delays your ember app starting until the device is ready. This means that as long you're doing it in "ember-land", you shouldn't ever have to wait for `deviceready` to fire. Do you have the [device plugin](https://github.com/apache/cordova-plugin-device) added to your project? 

Also in `chrome://inspect`, what does `device.platform` return. If `device` does not exist, you need the plugin. If it returns something other than "Android", that is why `device.isAndroid` returns false.

**Comment by jarredkenny** [comment]
Yes, I do have the device plugin installed. 

I am able to access device.platform however this.get('device.isAndroid') is still undefined.

```
setup: function(){
    Ember.Logger.log(this.get('device.isAndroid')); // logs undefined
    Ember.Logger.log(device.platform); // logs "Android"
}.on('init)
```

**Comment by jarredkenny** [comment]
Checking `this.get('device.isAndroid')` appears to work fine in a view but not within a controller. I have moved my UI logic to a view and my problem has been corrected.

**Comment by jakecraige** [comment]
I'm glad you figured out how to get it working in your case. I can't think of anything that would cause that honestly. Other than some type of race condition. One way to test that would be to try doing it in some sort of action you can trigger or do a timeout in the init before calling it. This seems like a bug if that's the case

**Comment by jarredkenny** [comment]
One more question, above you said "When this utils lib is added it actually delays your ember app starting until the device is ready.". 

Does it delay the loading of the application route, or delay the app from starting entirely? I ask because I am trying to implement a loading screen to be displayed until the `deviceready` event is fired and the application can start.

**Comment by jakecraige** [comment]
It delay's the app inside of an initialize using the [Ember.Application.deferReadiness](http://emberjs.com/api/classes/Ember.Application.html#method_deferReadiness) method. You could set up an initializer that run's before that which shows the splashscreen or include it in another place like your `app.js` file. Which is outside of the context of an ember app
